### ISSUE TITLE
spacemacs/load-theme

### ISSUE THREAD

**Issue by neeasade** [Devereux-Henley/Dotfiles#1]
What is the value in `spacemacs/load-theme` vs `load-theme`? curious -- currently doing an amout of stuff after load-theme call - https://git.io/v5cBM

**Comment by Devereux-Henley** [comment]
`spacemacs/load-theme` just has some logic for accessing cached themes vs installing a new theme package and some prettier error handling. It ends with a direct call to `load-theme`. The only reason I am making that call in the first place instead of placing `'gruvbox` in the `dotspacemacs-themes` list was as a workaround to [this issue](https://github.com/syl20bnr/spacemacs/issues/8090), an issue with themes being applied before `autothemer` was loaded. I believe there were a couple of other workarounds suggested but this is the one I rolled with at the time.

**Comment by neeasade** [comment]
I see, thanks

**Comment by neeasade** [comment]
do you use org mode much for task management? take a look at this http://www.nongnu.org/org-edna-el/#operation
